# Install scripts.
install:
  - npm install

# Post-install test scripts.
test_script:
  # Output useful for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off